server {
    listen 3000;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Это нужно, чтобы React Router работал при перезагрузке страницы
        try_files $uri $uri/ /index.html;
    }
}