package com.matchme.auth;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.time.OffsetDateTime;

// Map the existing users table in PostgreSQL
@Entity
@Table(name = "users")
public class User {

    // Database primary key generated by BIGSERIAL
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Email must be unique
    @Column(nullable = false, unique = true)
    private String email;

    // Stores the bcrypt hash, never the raw password
    @Column(name = "password_hash", nullable = false)
    private String passwordHash;

    // Created by PostgreSQL using the DEFAULT NOW() value.
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private OffsetDateTime createdAt;

    protected User() {
    }

    public User(String email, String passwordHash) {
        this.email = email;
        this.passwordHash = passwordHash;
    }

    public Long getId() {
        return id;
    }

    public String getEmail() {
        return email;
    }

    public String getPasswordHash() {
        return passwordHash;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }
}
